---
apiVersion: template.openshift.io/v1
kind: Template
objects:
  - apiVersion: tekton.dev/v1
    kind: Pipeline
    metadata:
      name: bulk-copy-images
      namespace: ${PIPELINES_PROJECT}
    spec:
      tasks:
        - name: skopeo-copy
          params:
            - name: srcTLSverify
              value: 'true'
            - name: destTLSverify
              value: 'true'
          taskRef:
            kind: ClusterTask
            name: skopeo-copy-fixed
          workspaces:
            - name: images-url
              workspace: images-url
      workspaces:
        - name: images-url
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: bulk-copy-images-configmap
      namespace: ${PIPELINES_PROJECT}
    data:
      url.txt: |
        docker://registry.redhat.io/ubi8/openjdk-17:1.15 docker://quay.io/alopezme/openjdk-17:1.15
        docker://registry.redhat.io/ubi8/openjdk-17:1.15 docker://quay.io/alopezme/pipelines-test:1.15
parameters:
  - name: PIPELINES_PROJECT
    description: "The project where the Pipelines will be deployed."
    required: false
    value: pipelines-test
