apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: int-test
spec:
  steps:
    - name: verify
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      command: ["sleep"]
      args: ["20"]