---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring-petclinic-maven-cache-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
