---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: copy-image-
  namespace: ocp-pipelines
  labels:
    tekton.dev/pipeline: copy-image
spec:
  params:
    - name: source-image
      value: registry.redhat.io/ubi8/openjdk-17:1.15
    - name: destination-image
      value: quay.io/alopezme/openjdk-17:1.15
  pipelineRef:
    name: copy-image
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - emptyDir: {}
      name: images-url
