---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: bulk-copy-images-
  namespace: ocp-pipelines
  labels:
    tekton.dev/pipeline: bulk-copy-images
spec:
  pipelineRef:
    name: bulk-copy-images
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: images-url
      configMap:
        name: bulk-copy-images-configmap
