---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: ocp-pipelines
  name: ocp-pipelines
  namespace: gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops
    repoURL: https://github.com/alvarolop/ocp-pipelines
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions: []
