= OpenShift Pipelines
Álvaro López Medina <alopezme@redhat.com>
v1.0, 2023-03
// Metadata
:description: This repository contains resources to deploy and test Openshift Pipelines
:keywords: openshift, pipelines, tekton, ci, red hat
// Create TOC wherever needed
:toc: macro
:sectanchors:
:sectnumlevels: 2
:sectnums: 
:source-highlighter: pygments
:imagesdir: images
// Start: Enable admonition icons
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:icons: font
endif::[]

This repository contains resources to deploy and practice Openshift Pipelines.

// Create the Table of contents here
toc::[]

== Introduction

*Red Hat OpenShift Pipelines* is a cloud-native, continuous integration and continuous delivery (CI/CD) solution based on Kubernetes resources. It uses Tekton building blocks to automate deployments across multiple platforms by abstracting away the underlying implementation details. 

**What do we understand as Cloud Native CI/CD?**

* *Containers*: Built for container apps and runs on Kubernetes.
* *Serverless*: Runs serverless with no CI/CD engine to manage and maintain.
* *DevOps*: Designed with microservices and distributed teams in mind.


To get more details, you can check the https://docs.openshift.com/container-platform/4.12/cicd/pipelines/understanding-openshift-pipelines.html[official documentation].


== Installation of the operator

Installing the operator is as easy as creating a Subscription in the project `openshift-operators`. The Pipelines Operator is installed for All namespaces: 

[source, bash]
----
oc apply -f 00-installation/1-subscription.yaml
----

In order to split the pipelines executing from the operator itself, we will create another namespace where the pipelines will be executed:

[source, bash]
----
cat 00-installation/2-project-template.yaml | \
PIPELINES_PROJECT=pipelines-test \
envsubst > 00-installation/2-project.yaml

oc apply -f 00-installation/2-project.yaml
----


== Useful Tasks for the pipelines

This section contains several tasks that can be useful for the pipelines. 


.*List files in the workspace*
[source, bash]
----
cat 10-tasks/1-list-files-template.yaml | \
PIPELINES_PROJECT=pipelines-test \
envsubst > 10-tasks/1-list-files.yaml

oc apply -f 10-tasks/1-list-files.yaml
----






== Secrets for authentication

In many practical use cases, you might need to pull from private Git repositories or might need to push to an external container registry such as Quay.io. In this section, we will summarize how to create the `Secrets` to configure all the credentials.

=== Red Hat registry


=== Git repository


=== Quay Robot Account








:sectnums!:
== Annex A: Tutorial

If you want a tutorial to learn Openshift Pipelines, I recommend you this https://redhat-scholars.github.io/tekton-tutorial/tekton-tutorial/index.html[tutorial] from Red Hat Scholars.

