---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sleep-pipeline
spec:
  params:
    - name: step1-sleep-duration
      description: Sleep duration for step 1 (in seconds)
      type: string
      default: 1
    - name: step2-sleep-duration
      description: Sleep duration for step 2 (in seconds)
      type: string
      default: 1
    - name: step3-sleep-duration
      description: Sleep duration for step 3 (in seconds)
      type: string
      default: 1
  tasks:
    - name: step1
      taskRef:
        name: sleep-task
      params:
        - name: sleep-duration
          value: $(params.step1-sleep-duration)

    - name: step2
      taskRef:
        name: sleep-task
      params:
        - name: sleep-duration
          value: $(params.step2-sleep-duration)
      runAfter:
        - step1

    - name: step3
      taskRef:
        name: sleep-task
      params:
        - name: sleep-duration
          value: $(params.step3-sleep-duration)
      runAfter:
        - step2
