---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-image-download
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  params:
    - description: Git repo SSH URL
      name: git-repo
      type: string
    - description: Folder in the Git repo where the Dockerfile and extra files are located.
      name: git-context
      default: "."
      type: string
    - description: Name of the image repository in Quay.
      name: image-name
      type: string
    - description: Tag of the image in Quay.
      name: image-tag
      type: string
  tasks:

    - name: git-clone
      params:
        - name: URL
          value: $(params.git-repo)
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: git-clone
      workspaces:
        - name: output
          workspace: git-repo

    - name: download-latest
      params:
        - name: organization
          value: kubernetes-sigs
        - name: repository
          value: kustomize
        - name: file-type
          value: linux_amd64
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: download-latest
      workspaces:
        - name: directory
          workspace: git-repo

    - name: list-files
      params:
        - name: path
          value: .
      runAfter:
        - download-latest
      taskRef:
        kind: Task
        name: list-files
      workspaces:
        - name: directory
          workspace: git-repo

    - name: chmod
      params:
        - name: file
          value: kustomize
        - name: permissions
          value: '554'
      runAfter:
        - list-files
      taskRef:
        kind: Task
        name: chmod
      workspaces:
        - name: directory
          workspace: git-repo

    - name: check-permissions
      params:
        - name: path
          value: .
      runAfter:
        - chmod
      taskRef:
        kind: Task
        name: list-files
      workspaces:
        - name: directory
          workspace: git-repo

    - name: buildah
      params:
        - name: IMAGE
          value: $(params.image-name):$(params.image-tag)
        # - name: CONTEXT
        #   value: $(params.dockerfile-path)
        - name: DOCKERFILE
          value: $(params.git-context)/Dockerfile
      runAfter:
        - check-permissions
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: buildah
      workspaces:
        - name: source
          workspace: git-repo
        # This only links one secret, but we need two. So we infer them from the SA
        # - name: dockerconfig
        #   workspace: docker-credentials
        - name: rhel-entitlement  
          workspace: rhel-entitlement
  workspaces:
    - name: git-repo
    # - name: docker-credentials
    - name: rhel-entitlement
