---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-image-entitlements
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  params:
    - description: Git repo SSH URL
      name: git-repo
      type: string
    - description: Folder in the Git repo where the Dockerfile and extra files are located.
      name: git-context
      default: "."
      type: string
    - description: Name of the image repository in Quay.
      name: image-name
      type: string
    - description: Tag of the image in Quay.
      name: image-tag
      type: string
  tasks:
    - name: git-clone
      params:
        - name: URL
          value: $(params.git-repo)
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: git-clone
      workspaces:
        - name: output
          workspace: git-repo
    - name: buildah
      params:
        - name: IMAGE
          value: $(params.image-name):$(params.image-tag)
        - name: CONTEXT
          value: $(params.git-context)
        - name: DOCKERFILE
          value: $(params.git-context)/Dockerfile
      runAfter:
        - git-clone
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: buildah
      workspaces:
        - name: source
          workspace: git-repo
        # This only links one secret, but we need two. So we infer them from the SA
        # - name: dockerconfig
        #   workspace: docker-credentials
        - name: rhel-entitlement  
          workspace: rhel-entitlement
  workspaces:
    - name: git-repo
    # - name: docker-credentials
    - name: rhel-entitlement
