---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocp-pipelines

resources:
  - task-buildah-with-entitlements.yaml
  - task-chmod.yaml
  - task-compose-repo-url.yaml
  - task-conditional-fail.yaml
  - task-copy-secret.yaml
  - task-download-release.yaml
  - task-echo-json.yaml
  - task-echo-message.yaml
  - task-extract-quay-env.yaml
  - task-list-files.yaml
  - task-skopeo-copy-fixed.yaml
  - task-sleep.yaml
