---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: conditional-fail
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  params:
    - name: force-failure
      description: Boolean to decide if the task fails
      type: string
      default: "true"
  steps:
    - name: check-failure-condition
      image: registry.access.redhat.com/ubi8/ubi-minimal
      script: |
        if [ "$(params.force-failure)" = "true" ]; then
          echo "Triggering intentional failure"
          exit 42
        fi