---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: copy-secret
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  params:
    - name: project
      description: Destination namespace.
      type: string
      default: ocp-pipelines
  steps:
    - name: echo
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli
      script: |
        #!/bin/sh
        if oc get secret etc-pki-entitlement -n openshift-config-managed &> /dev/null; then
          echo -e "The secret with the entitlements exists in the openshift-config-managed namespace. Proceed."
        else 
          echo -e "The secret with the entitlements does not exist in openshift-config-managed namespace. It might be an issue with OpenShift Insights. Skipping copy...exit"
          exit 0
        fi
        if oc get secret etc-pki-entitlement -n $(params.project) &> /dev/null; then
          echo -e "The secret with the entitlements exists already in $(params.project). Skipping copy...exit"
          exit 0
        fi
        oc get secret etc-pki-entitlement -n openshift-config-managed -o yaml \
          | sed s/"namespace: openshift-config-managed"/"namespace: $(params.project)"/\
          | oc create -f -
