---
apiVersion: template.openshift.io/v1
kind: Template
objects:
  - apiVersion: tekton.dev/v1
    kind: Task
    metadata:
      name: list-files
      namespace: ${PIPELINES_PROJECT}
    spec:
      params:
        - name: path
          description: Path to list files.
          type: string
          default: .
      workspaces:
        - name: directory
          description: The mounted directory to list files.
      steps:
        - name: echo
          # image: registry.access.redhat.com/ubi8/ubi
          image: image-registry.openshift-image-registry.svc:5000/openshift/cli
          script: |
            #!/bin/sh
            echo "List files in $(params.path):"
            ls -la $(params.path)
            echo "List files in $(workspaces.directory.path):"
            ls -la $(workspaces.directory.path)
parameters:
  - name: PIPELINES_PROJECT
    description: "The project where the Pipelines will be deployed."
    required: false
    value: pipelines-test
