---
apiVersion: template.openshift.io/v1
kind: Template
objects:
  - apiVersion: tekton.dev/v1
    kind: Task
    metadata:
      name: download-latest
      namespace: ${PIPELINES_PROJECT}
    spec:
      params:
        - name: organization
          description: GitHub organization of the repo.
          type: string
        - name: repository
          description: GitHub repository.
          type: string
        - name: file-type
          description: Selector of the release file.
          type: string
      workspaces:
        - name: directory
          description: The mounted directory to list files.
      steps:
        - name: echo
          # image: registry.access.redhat.com/ubi8/ubi
          image: image-registry.openshift-image-registry.svc:5000/openshift/cli
          script: |
            #!/bin/sh
            echo "Downloading latest release from $(params.organization)/$(params.repository) in $(workspaces.directory.path):"
            DOWNLOAD_URL=$(curl -s https://api.github.com/repos/$(params.organization)/$(params.repository)/releases/latest | grep browser_download_url | cut -d\" -f4 |  grep $(params.file-type))
            curl -sL $DOWNLOAD_URL --output $(workspaces.directory.path)/$(basename $DOWNLOAD_URL)
            tar xvf $(workspaces.directory.path)/$(basename $DOWNLOAD_URL) --directory $(workspaces.directory.path)/

parameters:
  - name: PIPELINES_PROJECT
    description: "The project where the Pipelines will be deployed."
    required: false
    value: pipelines