---
apiVersion: template.openshift.io/v1
kind: Template
objects:
  - apiVersion: tekton.dev/v1
    kind: Task
    metadata:
      name: copy-secret
      namespace: ${PIPELINES_PROJECT}
    spec:
      params:
        - name: project
          description: Destination namespace.
          type: string
          default: ${PIPELINES_PROJECT}
      steps:
        - name: echo
          image: image-registry.openshift-image-registry.svc:5000/openshift/cli
          script: |
            #!/bin/sh
            if oc get secret etc-pki-entitlement -n openshift-config-managed &> /dev/null; then
                echo -e "The secret with the entitlements exists already. Skipping copy...exit"
                exit 0
            fi
            oc get secret etc-pki-entitlement -n openshift-config-managed -o yaml \
              | sed s/"namespace: openshift-config-managed"/"namespace: $(params.project)"/\
              | oc create -f -
parameters:
  - name: PIPELINES_PROJECT
    description: "The project where the Pipelines will be deployed."
    required: false
    value: pipelines