{
 "title": "Alvaro's Tekton Overview",
 "description": "This is a dashboard for Tekton.\r\n",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "database", "label": "database", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "query_result(tekton_pipelines_controller_pipelinerun_duration_seconds_bucket)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Now",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running PipelineRun",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(tekton_pipelines_controller_running_pipelineruns_count)"
    }
   ]
  },
  {
   "title": "Running Taskrun",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(tekton_pipelines_controller_running_taskruns_count)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Running Pod",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Running\", namespace=~\"^$namespace$\"}>0)",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Pipelinerun Count List",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum by(pipeline) (tekton_pipelines_controller_pipelinerun_duration_seconds_count{namespace=~\"$namespace\", status=\"success\"})",
     "legendFormat": "{{`{{pipeline}}`}}"
    },
    {
     "expr": "sum by(pipeline) (tekton_pipelines_controller_pipelinerun_duration_seconds_count{namespace=~\"$namespace\", status=\"failed\"})",
     "legendFormat": "{{`{{pipeline}}`}}"
    }
   ]
  },
  {
   "title": "Pipelinerun Increase(5m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tekton_pipelines_controller_pipelinerun_count{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Pipelinerun",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (pipelinerun) (tekton_pipelines_controller_pipelinerun_duration_seconds_sum{}))"
    }
   ]
  },
  {
   "title": "Pipelinerun status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tekton_pipelines_controller_pipelinerun_duration_seconds_count{status=~\"success\", namespace=~\"$namespace\"})",
     "legendFormat": "{{`{{status}}`}}"
    },
    {
     "expr": "sum(tekton_pipelines_controller_pipelinerun_duration_seconds_count{status=~\"failed\", namespace=~\"$namespace\"})",
     "legendFormat": "{{`{{status}}`}}"
    }
   ]
  },
  {
   "title": "Top Tasks AVG",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(task)(tekton_pipelines_controller_pipelinerun_taskrun_duration_seconds_sum{namespace=~\"$namespace\", status=\"success\"}) / sum by(task) (tekton_pipelines_controller_pipelinerun_taskrun_duration_seconds_count{namespace=~\"$namespace\", status=\"success\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taskrun Duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by(pipeline) (tekton_pipelines_controller_pipelinerun_duration_seconds_sum{namespace=~\"$namespace\"}) / sum by(pipeline) (tekton_pipelines_controller_pipelinerun_duration_seconds_count{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top PipelineRun AVG",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(pipeline) (tekton_pipelines_controller_pipelinerun_duration_seconds_sum{namespace=~\"$namespace\", status=\"success\"}) / sum by(pipeline) (tekton_pipelines_controller_pipelinerun_duration_seconds_count{namespace=~\"$namespace\", status=\"success\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Nodes Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo|nodelocaldns|dummy0|cali.*|docker.*|tunl.*|kube.*|veth.*|br.*\"}[5m]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo|nodelocaldns|dummy0|cali.*|docker.*|tunl.*|kube.*|veth.*|br.*\"}[5m]))",
     "legendFormat": "Send"
    }
   ]
  },
  {
   "title": "All Nodes Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{device!=\"\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{device!=\"\"}[5m]))",
     "legendFormat": "Written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{device!=\"\"}[5m]))",
     "legendFormat": "io time"
    }
   ]
  }
 ]
}