---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

configMapGenerator:
  - name: tekton-dashboard-dashboard
    files:
      - dashboard.json=tekton-dashboard.json
    options:
      disableNameSuffixHash: true
  - name: tekton-overview-dashboard
    files:
      - dashboard.json=16559-tekton-overview.json
    options:
      disableNameSuffixHash: true
  - name: krci-tekton-overview-dashboard
    files:
      - dashboard.json=18321-krci-tekton-overview.json
    options:
      disableNameSuffixHash: true
  - name: alvaro-tekton-overview-dashboard
    files:
      - dashboard.json=alvaro-tekton-overview.json
    options:
      disableNameSuffixHash: true

resources:
  - grafanadashboard-tekton-dashboard.yaml
  - grafanadashboard-tekton-overview.yaml
  - grafanadashboard-krci-tekton-overview.yaml
  - grafanadashboard-alvaro-tekton-overview.yaml
