---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocp-pipelines

resources:
  - cronjob-copy-image.yaml
  - copy-image-eventlistener.yaml
  - copy-image-triggerbinding.yaml
  - copy-image-triggertemplate.yaml
...
