---
apiVersion: template.openshift.io/v1
kind: Template
objects:
  - apiVersion: project.openshift.io/v1
    kind: Project
    metadata:
      name: ${PIPELINES_PROJECT}
      annotations:
        openshift.io/description: "Openshift Pipelines namespace"
        openshift.io/display-name: "Pipelines Testing Project"
parameters:
  - name: PIPELINES_PROJECT
    description: "The project where the Pipelines will be deployed."
    required: false
    value: pipelines-test