---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: copy-entitlements
spec:
  tasks:
    - name: copy-secret
      taskRef:
        kind: Task
        name: copy-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: get-secret-pipeline
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ""
    resources:
      - secrets
---
apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: get-secret-pipeline
  namespace: openshift-config-managed
roleRef:
  kind: ClusterRole
  name: get-secret-pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: ocp-pipelines
