---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: bulk-copy-images
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  tasks:
    - name: skopeo-copy
      params:
        - name: srcTLSverify
          value: 'true'
        - name: destTLSverify
          value: 'true'
      taskRef:
        name: skopeo-copy-fixed
      workspaces:
        - name: images-url
          workspace: images-url
  workspaces:
    - name: images-url
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bulk-copy-images-configmap
data:
  url.txt: |
    docker://registry.redhat.io/ubi8/openjdk-17:1.15 docker://quay.io/alopezme/openjdk-17:1.15
    docker://registry.redhat.io/ubi8/openjdk-17:1.15 docker://quay.io/alopezme/pipelines-test:1.15
