---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: manual-approval-example
spec:
  tasks:
    - name: intro
      taskRef:
        kind: Task
        name: echo
      params:
        - name: message
          value: "This is the initial Task that is executed before the Manual Approval."
    - name: example-manual-approval-task
      taskRef:
        apiVersion: openshift-pipelines.org/v1alpha1
        kind: ApprovalTask
      params:
      - name: approvers
        value:
        - alopezme
        - dseveria
        - mvalledi
      - name: description
        value: Example manual approval task - please approve or reject
      - name: numberOfApprovalsRequired
        value: '2'
      - name: timeout
        value: '60m'
    - name: final
      taskRef:
        kind: Task
        name: echo
      params:
        - name: message
          value: "This Task was executed only because the approval was successful."
