---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: copy-images-
  namespace: $PIPELINES_PROJECT
  labels:
    tekton.dev/pipeline: copy-images
spec:
  params:
    - name: source-image
      value: registry.redhat.io/ubi8/openjdk-17:1.15
    - name: destination-image
      value: quay.io/alopezme/openjdk-17:1.15
  pipelineRef:
    name: copy-images
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - emptyDir: {}
      name: images-url
