---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: bulk-copy-images-
  namespace: pipelines-test
  labels:
    tekton.dev/pipeline: bulk-copy-images
spec:
  pipelineRef:
    name: bulk-copy-images
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: images-url
      configMap:
        name: bulk-copy-images-configmap
