---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocp-pipelines

resources:
  # Pipeline
  - pipeline-clone-build-push.yaml
  
  # Tasks
  - image-updater.yaml
  - int-test.yaml
  - maven.yaml
  - redeploy.yaml
  - s2i-java-11-binary.yaml

  # PVC to speed process up
  - pvc-app-source-pvc.yaml
  - pvc-spring-petclinic-maven-cache-pvc.yaml
