---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/instance: ocp-pipelines

resources:
  # It could be installed using RHOAI automation
  - operator 
  - tasks
  - pipelines
  - triggers
  - tekton-hub
  - spring-petclinic
