---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocp-pipelines

# All this example is based on siamaksade's work:
# https://github.com/siamaksade/pipelines-examples/blob/master/pipeline-argocd/pipelines/petclinic-pipeline-dev.yaml

# It requires this workaround:
# oc adm policy add-scc-to-user privileged -z pipeline -n ocp-pipelines

resources:
  # Pipeline
  - pipeline-petclinic-deploy-dev.yaml
  
  # Tasks
  - task-image-updater.yaml
  - task-int-test.yaml
  - task-maven.yaml
  - task-redeploy.yaml
  - task-s2i-java-11-binary.yaml

  # PVC to speed process up
  - pvc-app-source-pvc.yaml
  - pvc-spring-petclinic-maven-cache-pvc.yaml
