---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: int-test
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  steps:
    - name: verify
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      command: ["sleep"]
      args: ["20"]