---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: copy-image-binding
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  params:
    - name: source-image
      value: registry.redhat.io/ubi8/openjdk-17:1.15
    - name: destination-image
      value: quay.io/alopezme/openjdk-17:1.15
