---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocp-pipelines

resources:

  # Resources related to the CronJob EventListener to Build Images
  - copy-image-cronjob.yaml
  - copy-image-eventlistener.yaml
  - copy-image-triggerbinding.yaml
  - copy-image-triggertemplate.yaml

  # Resources for an alternative based on advanced Tekton Triggers
  - build-tekton-triggers-eventlistener.yaml
  - build-tekton-triggers-triggerbinding.yaml
  - build-tekton-triggers-triggertemplate.yaml
