---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns-ocp-pipelines.yaml
  - sub-openshift-pipelines-operator.yaml
  - manual-approval-gate.yaml

  # # Enable Tracing
  # - cm-config-tracing.yaml

  # Tekton Config
  - tektonconfig-config.yaml

  # Alerting
  - prometheusrule-pipelines-rules.yaml
