---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: ocp-pipelines

resources:
  # - operator # It will be installed using RHOAI automation
  - configuration
  - tasks
  - pipelines
  - triggers
  - tekton-hub
  - spring-petclinic
  - tekton-pipeline-example
...
